name: build_vs

on: [push, pull_request]

jobs:
  build_sln:
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@v1

      - name: build
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Tools\VsDevCmd.bat"
          msbuild /p:Configuration=Debug visual-studio-2017/StarterProject.sln
        shell: cmd

      - name: test
        run: |
          visual-studio-2017\x64\Debug\StarterProject.exe
